In [49]:
import pandas as pd

import requests
import json

import glob

In [11]:
def extract_data(ticker):
    if len(ticker)>0:
        apikey = "" # get your own keys add into your environment variables and modify the code here.
        api_url = "https://financialmodelingprep.com/api/v3/historical-market-capitalization/" + ticker + "?limit=1000&from=2021-01-01&to=2024-08-31&apikey=" + apikey
    
        # Make the API request
        response = requests.get(api_url)
    
        # Check if the request was successful (status code 200)
        if response.status_code == 200:
            response_data = response.json()
        
            # Save the JSON response to a file
            filename = ticker + ".json"
            with open(filename, 'w') as json_file:
                json.dump(response_data, json_file, indent=4)
        
            print(f"API response saved to " + filename)
        else:
            print(f"Failed to retrieve data from API. Status code: {response.status_code}")
    else:
        print(f"Invalid Ticker Symbol")

In [12]:
#extract_data('TSLA')

API response saved to TSLA.json

In [13]:
df = pd.read_csv("Top 1000 technology companies.csv")

In [14]:
df

,Ranking,Company,Market Cap,Stock,Country,Sector,Industry
0,1,Apple Inc.,$2.866 T,AAPL,United States,Technology,Consumer Electronics
1,2,Microsoft Corporation,$2.755 T,MSFT,United States,Technology,Software—Infrastructure
2,3,Nvidia Corporation,$1.186 T,NVDA,United States,Technology,Semiconductors
3,4,Broadcom Inc.,$495.95 B,AVGO,United States,Technology,Semiconductors
4,5,Taiwan Semiconductor Manufacturing Company Lim...,$487.64 B,2330,Taiwan,Technology,Semiconductors
...,...,...,...,...,...,...,...
995,996,"Henan Thinker Automatic Equipment Co.,Ltd.",$825.4 M,603508,China,Technology,Scientific & Technical Instruments
996,997,"transcosmos, Inc.",$819.5 M,9715,Japan,Technology,Information Technology Services
997,998,Yeahka Ltd,$819.3 M,9923,China,Technology,Software—Infrastructure
998,999,Beijing Wanji Technology Co. Ltd,$816.1 M,300552,China,Technology,Scientific & Technical Instruments
999,1000,Fujian Foxit Software Development Joint Stock ...,$811.5 M,688095,China,Technology,Software—Application

In [23]:
df[df['Country'] == 'United States'].head(100)

,Ranking,Company,Market Cap,Stock,Country,Sector,Industry
0,1,Apple Inc.,$2.866 T,AAPL,United States,Technology,Consumer Electronics
1,2,Microsoft Corporation,$2.755 T,MSFT,United States,Technology,Software—Infrastructure
2,3,Nvidia Corporation,$1.186 T,NVDA,United States,Technology,Semiconductors
3,4,Broadcom Inc.,$495.95 B,AVGO,United States,Technology,Semiconductors
7,8,Oracle Corporation,$282.01 B,ORCL,United States,Technology,Software—Infrastructure
...,...,...,...,...,...,...,...
163,164,"Jack Henry & Associates, Inc.",$12.14 B,JKHY,United States,Technology,Information Technology Services
164,165,"Pure Storage, Inc.",$11.63 B,PSTG,United States,Technology,Computer Hardware
168,169,"Paycom Software, Inc.",$11.34 B,PAYC,United States,Technology,Software—Application
169,170,ZoomInfo Technologies Inc.,$11.33 B,ZI,United States,Technology,Software—Application
171,172,"DocuSign, Inc.",$11.22 B,DOCU,United States,Technology,Software—Application

In [26]:
#df_extract = df[df['Ranking'] < 101]
df_extract = df[df['Country'] == 'United States'].head(200)

In [27]:
df_extract.shape

(200, 7)

In [28]:
for row in df_extract.itertuples():
    extract_data(row.Stock)

API response saved to AAPL.json
API response saved to MSFT.json
API response saved to NVDA.json
API response saved to AVGO.json
API response saved to ORCL.json
API response saved to ADBE.json
API response saved to CRM.json
API response saved to AMD.json
API response saved to CSCO.json
API response saved to INTC.json
API response saved to INTU.json
API response saved to QCOM.json
API response saved to TXN.json
API response saved to IBM.json
API response saved to NOW.json
API response saved to AMAT.json
API response saved to UBER.json
API response saved to LRCX.json
API response saved to ADI.json
API response saved to MU.json
API response saved to PANW.json
API response saved to FI.json
API response saved to KLAC.json
API response saved to SNPS.json
API response saved to ANET.json
API response saved to WDAY.json
API response saved to CDNS.json
API response saved to VMW.json
API response saved to SNOW.json
API response saved to CRWD.json
API response saved to APH.json
API response saved to DELL.json
API response saved to MSI.json
API response saved to 9MW.json
API response saved to ADSK.json
API response saved to MCHP.json
API response saved to FTNT.json
API response saved to SQ.json
API response saved to 1QZ.json
API response saved to CTSH.json
API response saved to DDOG.json
API response saved to FIS.json
API response saved to PLTR.json
API response saved to ON.json
API response saved to TTD.json
API response saved to IT.json
API response saved to GFS.json
API response saved to ZS.json
API response saved to ANSS.json
API response saved to HPQ.json
API response saved to CDW.json
API response saved to FICO.json
API response saved to MPWR.json
API response saved to MDB.json
API response saved to HUBS.json
API response saved to KEYS.json
API response saved to GLW.json
API response saved to NET.json
API response saved to SPLK.json
API response saved to FTV.json
API response saved to BR.json
API response saved to HPE.json
API response saved to TDY.json
API response saved to VRSN.json
API response saved to FLT.json
API response saved to PTC.json
API response saved to FSLR.json
API response saved to NTAP.json
API response saved to AKAM.json
API response saved to TYL.json
API response saved to NUAN.json
API response saved to SWKS.json
API response saved to EPAM.json
API response saved to ENPH.json
API response saved to ENTG.json
API response saved to JBL.json
API response saved to WDC.json
API response saved to SMCI.json
API response saved to TER.json
API response saved to DT.json
API response saved to LDOS.json
API response saved to SSNC.json
API response saved to GDDY.json
API response saved to NLOK.json
API response saved to U.json
API response saved to BSY.json
API response saved to OKTA.json
API response saved to AZPN.json
API response saved to AFRM.json
API response saved to ZBRA.json
API response saved to CTXS.json
API response saved to APP.json
API response saved to PATH.json
API response saved to TRMB.json
API response saved to MANH.json
API response saved to JKHY.json
API response saved to PSTG.json
API response saved to PAYC.json
API response saved to ZI.json
API response saved to DOCU.json
API response saved to NTNX.json
API response saved to MSTR.json
API response saved to ESTC.json
API response saved to FFIV.json
API response saved to QRVO.json
API response saved to DOX.json
API response saved to PFPT.json
API response saved to CDAY.json
API response saved to DBX.json
API response saved to BKI.json
API response saved to PLAN.json
API response saved to JNPR.json
API response saved to SNX.json
API response saved to ZEN.json
API response saved to PCOR.json
API response saved to CREE.json
API response saved to LSCC.json
API response saved to PCTY.json
API response saved to GWRE.json
API response saved to OLED.json
API response saved to WEX.json
API response saved to SWCH.json
API response saved to AVLR.json
API response saved to DLB.json
API response saved to BILL.json
API response saved to UI.json
API response saved to NATI.json
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429
Failed to retrieve data from API. Status code: 429

In [53]:
def merge_json_to_csv(file_pattern):
    # Get a list of file paths matching the pattern
    json_files = glob.glob(file_pattern)

    # Load each CSV file into a DataFrame and store it in a list
    dfs = [pd.read_json(file) for file in json_files]

    # Concatenate all DataFrames into one
    combined_df = pd.concat(dfs, ignore_index=True)

    combined_df.to_csv('MarketCap_History_Top-100_Companies.csv',index=False)

In [54]:
file_pattern = "extract_historical_data/*.json"
merge_json_to_csv(file_pattern)

In [55]:
df1 = pd.read_csv('MarketCap_History_Top-100_Companies.csv')

In [58]:
df1.head()

  symbol        date    marketCap
0   AZPN  2024-08-30  14822935120
1   AZPN  2024-08-29  14528552920
2   AZPN  2024-08-28  13894839840
3   AZPN  2024-08-27  13570702880
4   AZPN  2024-08-26  13539048880

In [60]:
df1.isna().sum()

symbol       0
date         0
marketCap    0
dtype: int64

In [62]:
df1.nunique()

symbol          116
date            921
marketCap    102566
dtype: int64